### PR TITLE
Add __repr__(s)

### LINKED ISSUE #54: `__repr__` for everyone!

### PR DESCRIPTION
**Pull request by ritzvik**
Fixes #54

### CODE REVIEW

**Comment by ritzvik** [comment]
@pmelchior Currently I have added __repr__ for `component.py` only as I was confused how to add it. Could you check it? If you give it a green flag, then I will add for the rest.

**Comment by ritzvik** [comment]
And I was trying the get the editable version installed, then this happened.
```
ERROR: Complete output from command 'c:\users\ritwik\appdata\local\programs\python\python36\python.exe' -c 'import setuptools, tokenize;__file__='"'"'F:\\Programming\\scarlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:
    ERROR: running develop
    running egg_info
    writing scarlet.egg-info\PKG-INFO
    writing dependency_links to scarlet.egg-info\dependency_links.txt
    writing requirements to scarlet.egg-info\requires.txt
    writing top-level names to scarlet.egg-info\top_level.txt
    reading manifest file 'scarlet.egg-info\SOURCES.txt'
    writing manifest file 'scarlet.egg-info\SOURCES.txt'
    running build_ext
    building 'scarlet.operators_pybind11' extension
    c:\users\ritwik\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py:479: UserWarning: The version specified ('0.4.f259857') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'c:\users\ritwik\appdata\local\programs\python\python36\python.exe' -c 'import setuptools, tokenize;__file__='"'"'F:\\Programming\\scarlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in F:\Programming\scarlet\
```
Any workarounds?

**Comment by pmelchior** [comment]
First, it's easier if you wait for a few days because we're in the middle of a substantial change.

Second, in order to install and run scarlet you need a module which requires a compiler. This is why you get the error message to install Visual C++. That said, we don't support Windows as platform, so it might work, or not. If you want to run scarlet, use linux (which can be installed in Windows, see e.g. [here](https://github.com/pmelchior/usrp-sciprog/blob/master/SETUP-INSTALLATION.md)).

**Comment by ritzvik** [comment]
@pmelchior Sure!

**Pull request closed without merging**
