### PR TITLE
Source cache

### PR DESCRIPTION
**Pull request by pmelchior**
Solves #30 by introducing a config module, so that source sizes (and other aspects of scarlet) can be shared across the package.

### CODE REVIEW

**Comment by fred3m** [comment]
I like the idea of having a configuration that can be used in multiple places, like `Source` and `Blend` objects, but I'd rather see a config class that can be passed around than a module. The main reason is to make it easier to persist the configuration used. With the scheme in this commit, the configuration used for a particular blend is lost if the same file creates multiple blend objects with different configuration parameters, which is reasonable when running the deblender on a new dataset and trying to find the optimal values for parameters.

**Comment by pmelchior** [comment]
It's a bit of a special case, but I see your point.

Also, it would allow to fix the source_sizes (namely at instantiation) instead of every time any piece of the code needs to access it. Wait for another commit ...

**Comment by pmelchior** [comment]
In retrospect, I should have thought about this a little longer. The idea of passing `config` around is counter to the intended purpose. It would need to be passed around only if there can be multiple instances in parallel, which isn't what will happen here. Therefore, I don't think `config` should be a class because you don't want to (have to) instantiate it, so it's all about static methods etc., and at that point you might just do it as a module, which is what I've done. That's the python way.

Moreover, I don't think the problem you mention ever arises in a production environment where persisting configs would be useful.

**Comment by fred3m** [comment]
All of the configs in the LSST stack are in a ConfigClass, not a module, for the purpose of persisting them. It is also useful for testing, where there may be multiple different configurations used in the same module to test how different parameters affect the result.

**Comment by pmelchior** [comment]
The purpose in the LSST stack probably arises from having multiple concurrent instances of `ConfigClass`. I can't see that being the case for the deblender.

As for testing, I doubt that you'd need to persist.

Anyway, should this ever become an issue, then we'll address it. This PR is about preventing misses in the transformation cache.

**Pull request merged**
